AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template para desplegar una instancia EC2 en us-east-2'

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Tipo de instancia EC2
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

Resources:
  # Security Group para la instancia
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para instancia EC2 MinTic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Allow SSH
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP
      Tags:
        - Key: Name
          Value: MinTic-EC2-SecurityGroup

  # Instancia EC2
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c80e2b6ccb9ad6d1  # Amazon Linux 2023 us-east-2 (Ohio)
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: MinTic-EC2-Instance

Outputs:
  InstanceId:
    Description: ID de la instancia EC2
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  PublicIP:
    Description: IP pública de la instancia
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  SecurityGroupId:
    Description: ID del Security Group
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'
